image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

stages:
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

deploy_stage:
  stage: deploy
  only:
    - development
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - cd dist/DatePoll-Frontend
    - ls
    - sshpass -V
    - export SSHPASS=$SSH_PASSWORD
    - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST 'cd /var/www/datepoll; rm -rf ./*;'
    - sshpass -e scp -o stricthostkeychecking=no -r . $SSH_USERNAME@$SSH_HOST:/var/www/datepoll
