image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

stages:
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

deploy_stage:
  stage: deploy
  only:
    - development
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - cd dist/
    - ls
    - sshpass -V
    - sshpass -p '$SSH_PASSWORD' scp -r -o UserKnownHostsFile=/dev/null -P $SSH_PORT ./DatePoll-Frontend/*  $SSH_USERNAME@$SSH_HOST:/var/www/datepoll/
