image: node:16.9.0

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm ngcc # Run npm-script ngcc, if ng build does it, the ci breaks (not enough memory)
    - mkdir -p dist/DatePoll-Frontend/ # Create dist folder, Angular sometimes does not do it
    - pnpm build:ci
    - cd dist/
    - ls -al

deploy-dev:
  stage: deploy
  dependencies:
    - build
  only:
    - development
  cache: {}
  script:
    - apt-get update -qq && apt-get install -y -qq zip openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cd dist/
    - zip -r DatePoll-Frontend-dev.zip ./DatePoll-Frontend >> /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./DatePoll-Frontend-dev.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/DatePoll/Frontend-Releases/ > /dev/null

deploy-release:
  stage: deploy
  dependencies:
    - build
  only:
    - tags
  except:
    - branches
  cache: {}
  script:
    - apt-get update -qq && apt-get install -y -qq zip git openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - version=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd dist/
    - zip -r "DatePoll-Frontend-${version}.zip" ./DatePoll-Frontend >> /dev/null
    - cp "DatePoll-Frontend-${version}.zip" DatePoll-Frontend-latest.zip
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./DatePoll-Frontend-latest.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/DatePoll/Frontend-Releases/ > /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR "DatePoll-Frontend-${version}.zip" $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/DatePoll/Frontend-Releases/ > /dev/null
