name: Testing

on:
  push:
    branches:
      - '*' # matches every branch that doesn't contain a '/'
      - '*/*' # matches every branch containing a single '/'
      - '**' # matches every branch
      - '!main'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-prod:
    name: Build prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v1
        with:
          install: true

      - name: build
        run: |
          pnpm ngcc # Run npm-script ngcc, if ng build does it, the ci breaks (not enough memory)
          pnpm build:prod

      - uses: actions/upload-artifact@master
        name: upload artifact
        with:
          name: DatePoll-Frontend-dev
          path: ./dist/DatePoll-Frontend
          retention-days: 1
  deploy-testing:
    needs: [build-testing]
    name: Deploy testing
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/download-artifact@master
        with:
          name: DatePoll-Frontend-dev
          path: ./dist/DatePoll-Frontend

      - name: make zip
        run: |
          cd dist/
          ls -la
          zip -r DatePoll-Frontend-dev.zip ./DatePoll-Frontend >> /dev/null
          cd -

      - name: copy build to release server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./dist/DatePoll-Frontend-dev.zip
          remote: /var/www/datepoll-share/DatePoll/Frontend-Releases/DatePoll-Frontend-dev.zip
          host: ${{ secrets.RELEASES_SSH_HOST }}
          port: ${{ secrets.RELEASES_SSH_PORT }}
          username: ${{ secrets.RELEASES_SSH_USER }}
          privateKey: ${{ secrets.RELEASES_SSH_PRIVATE_KEY }}